#!/usr/bin/env bash
# Summary: Configure the shell environment for phpenv
# Usage: eval "$(phpenv init - [--no-rehash] [<shell>])"

set -e
[ -n "$PHPENV_DEBUG" ] && set -x

print=""
no_rehash=""
for args in "$@"
do
  if [ "$args" = "-" ]; then
    print=1
		shift
  fi

  if [ "$args" = "--no-rehash" ]; then
    no_rehash=1
    shift
  fi
done

shell="$1"
if [ -z "$shell" ]; then
  shell="$(basename "$SHELL")"
fi

resolve_link() {
  $(type -p greadlink readlink | head -1) $1
}

abs_dirname() {
  local cwd="$(pwd)"
  local path="$1"

  while [ -n "$path" ]; do
    cd "${path%/*}"
    local name="${path##*/}"
    path="$(resolve_link "$name" || true)"
  done

  pwd
  cd "$cwd"
}

root="$(abs_dirname "$0")/.."

if [ -z "$print" ]; then
  case "$shell" in
  bash )
    profile='~/.bash_profile'
    ;;
  zsh )
    profile='~/.zshrc'
    ;;
  ksh )
    profile='~/.profile'
    ;;
  fish )
    profile='~/.config/fish/config.fish'
    ;;
  * )
    profile='your profile'
    ;;
  esac

  { echo "# Load phpenv automatically by adding"
    echo "# the following to ${profile}:"
    echo
    case "$shell" in
    fish )
      echo 'status --is-interactive; and source (phpenv init -|psub)'
      ;;
    * )
      echo 'eval "$(phpenv init -)"'
      ;;
    esac
    echo
  } >&2

  exit 1
fi

mkdir -p "${PHPENV_ROOT}/"{shims,versions}

case "$shell" in
fish )
  echo "set -gx PATH '${PHPENV_ROOT}/shims' \$PATH"
  ;;
* )
  echo 'export PATH="'${PHPENV_ROOT}'/shims:${PATH}"'
  ;;
esac

case "$shell" in
bash | zsh | fish )
  echo "source \"$root/completions/phpenv.${shell}\""
  ;;
esac

if [ -z "$no_rehash" ]; then
  echo 'phpenv rehash 2>/dev/null'
fi

commands=(`phpenv-commands --sh`)
case "$shell" in
fish )
  cat <<EOS
function phpenv
  set command \$argv[1]
  set -e argv[1]
  switch "\$command"
  case ${commands[*]}
    source (phpenv "sh-\$command" \$argv|psub)
  case '*'
    command phpenv "\$command" \$argv
  end
end
EOS
  ;;
ksh )
  cat <<EOS
function phpenv {
  typeset command
EOS
  ;;
* )
  cat <<EOS
phpenv() {
  local command
EOS
  ;;
esac

if [ "$shell" != "fish" ]; then
IFS="|"
cat <<EOS
  command="\$1"
  if [ "\$#" -gt 0 ]; then
    shift
  fi

  case "\$command" in
  ${commands[*]})
    eval \`phpenv "sh-\$command" "\$@"\`;;
  *)
    command phpenv "\$command" "\$@";;
  esac
}
EOS
fi
